name: Build

on:
  push:

jobs:
  python-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit-tests:
    needs: python-formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt  # Make sure you have a requirements.txt
      - name: Run unit tests
        run: pytest  # Run your tests with pytest

  deploy-to-impaas:
    needs: python-tests  # Update to depend on python-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: cih124-sse-app
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM
